/// <reference lib="webworker" />
import { clientsClaim, skipWaiting } from "workbox-core";
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";
import { NetworkFirst, CacheFirst } from "workbox-strategies";
import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { ExpirationPlugin } from "workbox-expiration";

declare let self: ServiceWorkerGlobalScope;

// Activate new SW immediately without waiting for tabs to close
skipWaiting();

// Take control of all clients immediately
clientsClaim();

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// Precache all assets generated by the build (JS, CSS, HTML, icons, manifest)
// self.__WB_MANIFEST is injected by workbox-build
precacheAndRoute(self.__WB_MANIFEST);

// Cache images with CacheFirst strategy (for any images not in precache)
registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst({
    cacheName: "images",
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Use NetworkFirst for navigation requests (HTML)
// Falls back to cache after 3 seconds if network is slow
const navigationRoute = new NavigationRoute(
  new NetworkFirst({
    cacheName: "pages",
    networkTimeoutSeconds: 3,
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
  })
);
registerRoute(navigationRoute);

